language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

# Travis whitelists the installable packages, additions can be requested
#   https://github.com/travis-ci/apt-package-whitelist
addons:
  apt:
    packages:
      - swig

# Save pip's downloads/packages/wheels between job runs
cache:
  directories:
    - $HOME/.cache/pip

python:
  - 2.7
env:
  - DJANGO_PACKAGE="Django>=1.8,<1.9"
  - DJANGO_PACKAGE="Django>=1.9rc1,<1.10"
install:
  - pip install --upgrade pip wheel
  - pip install -q $DJANGO_PACKAGE 
  - pip install --pre -e .
  - pip install -r ./testproj/requirements.txt
  - pip freeze
script: ./testproj/manage.py test testproj
