language: python
env:
  matrix:
    - DJANGO_PACKAGE=https://github.com/django/django/archive/stable/1.6.x.tar.gz
    - DJANGO_PACKAGE=https://github.com/django/django/archive/stable/1.7.x.tar.gz
    - DJANGO_PACKAGE=https://github.com/django/django/archive/stable/1.8.x.tar.gz
install:
  - sudo apt-get install swig
  - pip install --upgrade pip
  - pip install -q $DJANGO_PACKAGE 
  - pip install -e .
  - pip install -r ./testproj/requirements.txt
  - pip freeze
script: ./testproj/manage.py test testproj
